// Code generated by `mygo generate`. DO NOT EDIT.

import { call } from "mygo-runtime";

// ---- Types ----

/** FileResult is the outcome of morphing a whole clip. */
export interface FileResult {
  /** base64 16-bit PCM WAV, 48 kHz mono */
  wav: string;
  /** output duration */
  seconds: number;
  /** input sample rate */
  inHz: number;
  /** output sample rate */
  outHz: number;
  /** DSP wall time, ms */
  elapsed: number;
}

export interface Params {
  pitch: number;
  timbre: number;
  strength: number;
  gain: number;
  bypass: boolean;
  eqPre: number[];
  eqPost: number[];
}

export interface Preset {
  id: string;
  name: string;
  nameZh: string;
  hint: string;
  params: Params;
}

/** State is everything the UI needs on load. */
export interface State {
  params: Params;
  presets: Preset[];
  eqFreqs: number[];
  sampleRate: number;
  latencyMs: number;
  platform: string;
}

// ---- Services ----

/** Morpher is the bound service: the page calls these methods. */
export const Morpher = {
  /**
   * ApplyPreset switches to a named voice and returns its parameters so the
   * UI can reflect them on the sliders.
   */
  applyPreset(id: string): Promise<Params> {
    return call("Morpher.ApplyPreset", id);
  },
  /** GetParams returns the current morph parameters. */
  getParams(): Promise<Params> {
    return call("Morpher.GetParams");
  },
  /** GetState returns params, presets and constants for the UI. */
  getState(): Promise<State> {
    return call("Morpher.GetState");
  },
  /**
   * ProcessChunk morphs one realtime block: base64 little-endian float32
   * mono at 48 kHz in, same format out. The (streamID, seq) pair makes a
   * reordered or timed-out call a deterministic rejection instead of an
   * out-of-turn stream-state mutation — see Morpher.ProcessChunk.
   */
  processChunk(streamID: number, seq: number, pcm: string): Promise<string> {
    return call("Morpher.ProcessChunk", streamID, seq, pcm);
  },
  /** ProcessFile morphs a whole WAV clip offline and returns a 48 kHz WAV. */
  processFile(wavB64: string): Promise<FileResult> {
    return call("Morpher.ProcessFile", wavB64);
  },
  /**
   * ResetStream begins a monitor epoch: streaming state is rebuilt and
   * the resolved value is the stream-ID base this monitor's chunks must
   * carry (base + resync index). Older streams are rejected from then on.
   */
  resetStream(): Promise<number> {
    return call("Morpher.ResetStream");
  },
  /** SetParams applies a new parameter set. */
  setParams(p: Params): Promise<void> {
    return call("Morpher.SetParams", p);
  },
} as const;
